services:

  database:
    container_name: keycloak_database
    hostname: keycloak_database
    image: mariadb:11.8.3
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloak
    healthcheck:
        test: ["CMD", "mariadb-admin", "-ukeycloak", "-pkeycloak", "ping"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - database:/var/lib/mysql:rw
    networks:
      - database

  keycloak:
    container_name: keycloak
    hostname: keycloak
    build: ./build
    restart: unless-stopped
    command: ["start-dev", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"]
    healthcheck:
      test: curl --silent --fail -A healthcheck -k https://localhost:8443/realms/master > /dev/null || exit 1
      interval: 60s
      timeout: 10s
    ports:
      - 8080:8080
    environment:
      REGISTRY_GROUP_PREFIX: registry- #registry-
      REGISTRY_CATALOG_AUDIENCE: editor #user|editor
      REGISTRY_NAMESPACE_SCOPE: group,domain,sld,username #group|domain|sld|username
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info #info|debug|trace
      KC_LOG_CONSOLE_OUTPUT: default # json|default
      KC_LOG_FILE_OUTPUT: default # json|default
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://database:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
        - database
    networks:
      - database

volumes:
  database:
    
networks:
  database: